services:
  nginx:
    image: 'nginx:1.25.3'
    volumes:
    # nginx.conf — главный файл конфигурации nginx. Находится в папке /etc/nginx
    # что то не то со штаными нстройками  
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    
    # dev.conf содержит специфические настройки для одного конкретного сайта
     - ./nginx/dev.conf:/etc/nginx/sites-enabled/dev.conf
     - ./www:/usr/share/nginx/html/index.php
     - ./www:/var/www
    
    # пробрасываем порт чтоб можно было смотреть не на VM 
    # Левая часть (3030): порт на хост-машине
    # Правая часть (80): порт внутри контейнера
    ports:
      - 3030:80
        
    healthcheck:
      test: curl -sS http://nginx | grep -c works > /dev/null
      interval: 5s
      timeout: 5s
      retries: 2
      start_period: 5s

  php:
    build: .
    ports:
      - 9000:9000
    volumes:
      - ./www:/var/www
